mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.todos_list, name='index'),
    path('add_todos/', views.add_todos, name='add_todos'),
    path('finish_todo/', views.finish_todo, name='finish_todo'),
    path('notfinish_todo/', views.notfinish_todo, name='notfinish_todo'),
    path('del_todo/', views.del_todo, name='del_todo'),
    path('active/', views.active, name='active'),
    path('completed/', views.completed, name='completed'),
]

todos/models.py
from django.db import models

class todos(models.Model):
    todo = models.CharField(max_length=100)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.todo

todos/views.py
from django.shortcuts import render
from django.views.generic import ListView
from todos.models import todos
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def todos_list(request):
    todo_list = todos.objects.all()
    context = {'todo_list': todo_list}
    return render(request, 'todos/todos_list.html', context)


def add_todos(request):
    add_todo = request.POST['todo']
    pichu = request.POST['pichu']
    Todos = todos()
    Todos.todo = add_todo
    Todos.save()
    return HttpResponseRedirect(reverse('todos:{}'.format(pichu)))

def finish_todo(request):
    todo_id = request.POST['pikachu']
    pichu = request.POST['pichu']
    todos.objects.filter(id=todo_id).update(completed=True)
    return HttpResponseRedirect(reverse('todos:{}'.format(pichu)))

def notfinish_todo(request):
    todo_id = request.POST['pikachu']
    pichu = request.POST['pichu']
    todos.objects.filter(id=todo_id).update(completed=False)
    return HttpResponseRedirect(reverse('todos:{}'.format(pichu)))

def del_todo(request):
    todo_id = request.POST['pikachu']
    pichu = request.POST['pichu']
    todos.objects.filter(id=todo_id).delete()
    return HttpResponseRedirect(reverse('todos:{}'.format(pichu)))

def active(request):
    active_todo = todos.objects.filter(completed=False)
    context = {'todo_list': active_todo}
    return render(request, 'todos/todos_list.html', context)

def completed(request):
    completed_todo = todos.objects.filter(completed=True)
    context = {'todo_list': completed_todo}
    return render(request, 'todos/todos_list.html', context)

todos/templates/index.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}이벤트 - TODOS{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href='{% static "css/style.css" %}'>
</head>
<body>
<section class="todoapp">
  <div id="sidebar">
    {% block sidebar %}
    {% endblock %}
  </div>
  <div class="main" id="todo_list">
    {% block todo_list %}{% endblock %}
  </div>
  <div class="count-container" id="count">
    {% block count %}
    {% endblock %}
  </div>
</section>
<script src="js/app.js"></script>
</body>
</html>

todos/templates/todos/todos_list.html
{% extends "index.html" %}

{% block sidebar %}
<h1>TODOS</h1>
    <form action="{% url 'todos:add_todos' %}" method="post">
      {% csrf_token %}
    <input id="new-todo-title" type="text" name="todo" class="new-todo" placeholder="할일을 추가해주세요" autofocus>
    <input type="hidden" name="pichu" value="index">
    </form>
{% endblock sidebar %}

{% block todo_list %}
    <input class="toggle-all" type="checkbox">
    <ul id="todo-list" class="todo-list">
        {% for todo in todo_list %}
        {% if todo.completed %}
        <li class="completed">
        {% else %}
        <li>
        {% endif %}
            <div class="view">
            {% if todo.completed %}
                <form action="{% url 'todos:notfinish_todo' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="pikachu" value="{{ todo.id }}">
                    <input type="hidden" name="pichu" value="index">
                    <input type="submit" value="해야한다">
                </form>
            {% else %}
                <form action="{% url 'todos:finish_todo' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="pikachu" value="{{ todo.id }}">
                    <input type="hidden" name="pichu" value="index">
                    <input type="submit" value="했다">
                </form>
            {% endif %}
            <label class="label">{{ todo.todo }}</label>
            <form action="{% url 'todos:del_todo' %}" method="post">
                {% csrf_token %}
            <button class="destroy" name="pikachu" value="{{ todo.id }}"></button>
                <input type="hidden" name="pichu" value="index">
            </form>
            </div>
            <input class="edit" value="">
        </li>
        {% endfor %}
{% endblock todo_list %}

        {% block count %}
        <span class="todo-count">총 <strong>{{ todo_list|length }}</strong> 개</span>
        <ul class="filters">
            <li><a class="all selected" href="/todos">전체보기</a></li>
            <li><a class="active" href="/todos/active">해야할 일</a></li>
            <li><a class="completed" href="/todos/completed">완료한 일</a></li>
        </ul>
        {% endblock count %}